@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(rec, "Recruiter", "Levio employee.")
Person(tad, "Technical advisor", "Levio employee.")
System_Ext(es, "E-mail system", "The internal e-mail system.")
System_Ext(mbs, "Unit4 System", "Stores all of the information about technical advisors, etc.")
System_Boundary(ibs, "Recruiting system") {
    Container(wa, "Reverse proxy", "NGINX", "Delivers the static content and the recruiting single page application.")
    Container(spa, "Single Page Application", "Typescript and Angular", "Provides all the recruiting system functionality to recruiter/technical advisor via their web browser.")
    Container(ma, "Mobile App", "Xamarin", "Provides a limited subset ot recruiting system functionality to recruiter/technical advisor via their mobile device.")
    Container(db, "Database", "Relational Database Schema", "Stores interview information, technical advisors, job positions, etc.")
    Container(api, "API Application", "Java and Spring Boot", "Provides recruiting system functionality via a JSON/HTTPS API.")

    Rel(api, es, "Sends e-mails", "SMTP")
    Rel(api, mbs, "Uses", "HTTPS")
    Rel(api, db, "Reads & writes to", "JDBC")
    Rel(wa, spa, "Delivers")
    Rel(spa, api, "Uses", "JSON/HTTPS")
    Rel(ma, api, "Uses", "JSON/HTTPS")
}

Rel(rec, wa, "Uses", "HTTPS")
Rel(rec, spa, "Uses")
Rel(rec, ma, "Uses")
Rel(es, rec, "Sends e-mails to")

Rel(tad, wa, "Uses", "HTTPS")
Rel(tad, spa, "Uses")
Rel(tad, ma, "Uses")
Rel(es, tad, "Sends e-mails to")
@enduml
